name: sailer

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sailer -d sailer"]
      interval: 5s
      timeout: 5s
      retries: 5

  s3:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    container_name: s3
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: "always"
    command: "pgsailer"
    env_file:
      - .env
    volumes:
      - ./backups:/app/backups
      - ./keys:/app/age
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      
    
volumes:
  postgres_db_data:
  s3_data: