name: docpgsailer

services:
  postgres_db:
    image: postgres:15
    container_name: poostgres_db
    environment:
      - POSTGRES_PASSWORD=securePassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

volumes:
  postgres_db_data: