name: sailer

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=sailer
      - POSTGRES_USER=sailer
      - POSTGRES_PASSWORD=sailer
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sailer -d sailer"]
      interval: 5s
      timeout: 5s
      retries: 5

  s3:
    image: minio/minio:latest
    command: server --console-address ":9001" /data
    container_name: s3
    environment:
      - MINIO_ACCESS_KEY=mainioadmin
      - MINIO_SECRET_KEY=mainioadmin
      - MINIO_ROOT_USER=mainioadmin
      - MINIO_ROOT_PASSWORD=mainioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: "always"
    command: "pgsailer"
    environment:
      - POSTGRES_USER=sailer
      - POSTGRES_PASSWORD=sailer
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - BACKUP_SCHEDULE=*/2 * * * *
    volumes:
      - ./:/app
      - ./logs:/app/logs
      - ./backups:/root/backups
    depends_on:
      db:
        condition: service_healthy
      s3:
        condition: service_healthy
      
    
volumes:
  postgres_db_data:
  s3_data: